---
- hosts: all
  become: yes 
  become_method: sudo
  remote_user: centos

  tasks:

  - name: install java
    yum:
      name: java
      state: present

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /usr/share/tomcat
      createhome: no
  - name: create /opt/tomcat9 directory
    file:
      path: /opt/tomcat9
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: http://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.24/bin/apache-tomcat-9.0.24.tar.gz
      dest: /opt/tomcat9
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership
    file:
      path: /opt/tomcat9
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Start and enable Tomcat service
    systemd:  
   
      name: tomcat
      state: started       
      enabled: true
      daemon_reload: true
      command: nohup '/opt/tomcat/bin/startup.sh'
