- hosts:  all
  become: yes
  tasks:
    - name: Install Web Server
      package:
        name: tomcat
        state: installed

    - name: Start Web Server
      service:
        name: tomcat
        state: started
        enabled: yes
