- hosts: webservers
  remote_user: test
  become: yes
  become_method: sudo
  tasks: 
    - name: Install system updates for Red Hat systems
      yum: name=* state=latest update_cache=yes
      when: ansible_distribution == "CentOS"

