- hosts: webservers
  remote_user: test
  become: yes
  become_method: sudo
  tasks:
  - name: Install Sysadmin Packages
    yum: pkg={{ item }} state=installed update_cache=yes
    with_items:
        - vim
        - wget
        - curl
        - bash
        - ethtool
        - binutils
        - nfs-utils
        - pam
        - procps-ng
        - psmisc
        - smartmontools
        - unzip
        - sysstat
