- hosts: webservers
  remote_user: test
  become: yes
  become_method: sudo
  tasks: 
  - name: Allow user babinlonston to manage Docker
    user:
      name: babinlonston
      groups: docker
      append: yes
