- hosts: webservers 
  remote_user: test
  become: yes
  become_method: sudo
  tasks:
    - name: Enable red hat Optional Repository
      command:
           subscription-manager repos --enable rhel-7-server-optional-rpms
