---
- hosts: webservers
  remote_user: test
  become: yes
  tasks: 
  - name: install httpd package
    yum: 
      name: httpd 
      state: installed
  - name: copy index.html 
    copy: 
      src: /etc/ansible/index.html  
      dest: /var/www/html/
  - name: service httpd start
    service: 
      name: httpd 
      state: started
      
    


